# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import submission_pb2 as submission__pb2


class SubmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitSnapshot = channel.stream_unary(
                '/submission.Submission/SubmitSnapshot',
                request_serializer=submission__pb2.SnapshotSubmission.SerializeToString,
                response_deserializer=submission__pb2.SubmissionResponse.FromString,
                )


class SubmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitSnapshot(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitSnapshot': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitSnapshot,
                    request_deserializer=submission__pb2.SnapshotSubmission.FromString,
                    response_serializer=submission__pb2.SubmissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'submission.Submission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Submission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitSnapshot(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/submission.Submission/SubmitSnapshot',
            submission__pb2.SnapshotSubmission.SerializeToString,
            submission__pb2.SubmissionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
